SwiftFoodie/Models/Restaurants.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SwiftFoodie.Models
{
    public partial class Restaurants
    {
        [Key]
        public long RestaurantID { get; set; }
        public string RestaurantName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string OwnerName { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string CompleteAddress { get; set; }
        public bool IsActive { get; set; }
    }
}

SwiftFoodie/Areas/Admin/Controllers/RestaurantController.cs
using SwiftFoodie.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SwiftFoodie.Areas.Admin.Controllers
{
    public class RestaurantController : Controller
    {
        DBContextDataBase db = new DBContextDataBase();
        // GET: Admin/Restaurant
        public ActionResult Add()
        {
            return View();
        }

        public ActionResult SaveRestaurant(Restaurants restaurants)
        {
            if (restaurants.RestaurantID == 0)
            {
                restaurants.IsActive = true;
                db.Restaurants.Add(restaurants);
               
            }
            else
            {
                db.Entry(restaurants).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("all");
        }
        public ActionResult All()
        {
            var Rest = db.Restaurants.ToList();
            return View(Rest);
        }
        public ActionResult Edit(long id)
        {
            var res = db.Restaurants.Find(id);
            if (res !=null)
            {
                return View(res);
            }
            else
            {
                return RedirectToAction("");
            }

        }
        public ActionResult DeleteConfirm(long id)
        {
            var res = db.Restaurants.Find(id);
            if (res != null)
            {
                return View(res);
            }
            else
            {
                return RedirectToAction("");
            }

        }
        public ActionResult Delete(long id)
        {
            Restaurants res = db.Restaurants.Find(id);
            if (res != null)
            {
                res.IsActive = false;
                db.Entry(res).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("all");
        }
        public ActionResult dlist()
        {
            var Rest = db.Restaurants.Where(r => r.IsActive == false).ToList();
            return View(Rest);
        }
        public ActionResult alist()
        {
            var Rest = db.Restaurants.Where(r => r.IsActive == true).ToList();
            return View(Rest);
        }
        public ActionResult doactive(long id)
        {
            Restaurants res = db.Restaurants.Find(id);
            if (res != null)
            {
                res.IsActive = true;
                db.Entry(res).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("dlist");
        }
    }
}

SwiftFoodie/Areas/Admin/Views/Restaurant/Add.cshtml
@using System.Web.Configuration

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,700">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/elephant.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/application.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/demo.min.css">
}

<div class="layout-content-body">
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib">New Restaurant Form</span>
           
        </h1>
    </div>
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <form action="saverestaurant" method="post">
                <div class="demo-md-form-wrapper">
                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" name="RestaurantName" type="text">
                        <label class="md-control-label">Restaurant Name</label>
                    </div>

                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" name="UserName" type="text">
                        <label class="md-control-label">User Name</label>
                    </div>
                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" name="Password" type="text">
                        <label class="md-control-label">Password</label>
                    </div>

                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" name="OwnerName" type="text">
                        <label class="md-control-label">Owner Name</label>
                    </div>
                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" name="PhoneNumber" type="text">
                        <label class="md-control-label">Owner Phone Number</label>
                    </div>

                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" name="City" type="text">
                        <label class="md-control-label">City</label>
                    </div>
                    <div class="md-form-group md-label-floating">
                        <textarea class="md-form-control" rows="4" name="CompleteAddress" maxlength="512"></textarea>
                        <label class="md-control-label">Complete Address</label>
                    </div>
                    <div class="md-form-group md-label-floating">
                        <button class="btn btn-outline-primary btn-pill" type="submit">Save</button>
                        <a href="@Url.Action("dashboard","home")" class="btn btn-outline-danger btn-pill pull-right" type="reset">Cancel</a>
                    </div>
                </div>
            </form>
         
        </div>
    </div>
</div>
@section scripts{
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/vendor.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/elephant.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/application.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/demo.min.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-83990101-1', 'auto');
        ga('send', 'pageview');
    </script>
}

SwiftFoodie/Areas/Admin/Views/Restaurant/All.cshtml
@using System.Web.Configuration
@model IEnumerable<SwiftFoodie.Models.Restaurants>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,700">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/elephant.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/application.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/demo.min.css">
}

<div class="layout-content-body">
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib">Restaurants List</span>
            
        </h1>
    </div>
    
   
    <div class="row gutter-xs">
        @if (Model.Count() > 0)
        {
            foreach (var c in Model) // Print the list
            {
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <div class="media">
                                <div class="media-middle media-body">
                                    <a class="link-muted" href="#">
                                        <strong>@c.OwnerName</strong>
                                    </a>

                                    <a class="link-muted" href="#">
                                        <strong>@c.PhoneNumber</strong>
                                    </a>
                                    <span class="badge badge-@(c.IsActive==false?"danger":"")  pull-right"> In-Active</span>
                                </div>
                            </div>
                        </div>
                        <div class="card-image">
                            <a class="card-link" href="#">
                                <img class="img-responsive" src="@WebConfigurationManager.AppSettings["Theme"]img/8160313374.jpg" alt="Restaurant Magnifique">
                            </a>
                        </div>

                        <div class="card-body">
                            <h4 class="card-title text-center">@c.RestaurantName</h4>
                            <p class="card-text text-center">
                                <small>@c.CompleteAddress</small>
                            </p>
                        </div>
                        <div class="card-footer">
                            <a href="edit/@c.RestaurantID" class="btn btn-default" type="button">Update</a>
                            @if (c.IsActive == true)
                            {
                                <a href="deleteconfirm/@c.RestaurantID" class="btn btn-danger pull-lg-right" type="button">Delete</a>
                            }
                            else
                            {
                                <a href="doactive/@c.RestaurantID" class="btn btn-success pull-lg-right" type="button">Do Active</a>

                            }
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="card mt-5">
                <div class="card-body text-center">
                    <div class="alert alert-fill-danger text-danger" role="alert">
                        <i class="icon icon-exclamation-circle"></i>
                        Sorry, Nothing Found
                    </div>
                </div>
            </div>
        }

    </div>
</div>
@section scripts{
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/vendor.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/elephant.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/application.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/demo.min.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-83990101-1', 'auto');
        ga('send', 'pageview');
    </script>
}

SwiftFoodie/Areas/Admin/Views/Restaurant/DeleteConfirm.cshtml
@using System.Web.Configuration
@model SwiftFoodie.Models.Restaurants

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,700">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/elephant.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/application.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/demo.min.css">
}

<div class="layout-content-body">
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib">Delete Confirmation @Model.RestaurantName</span>

        </h1>
    </div>
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="demo-md-form-wrapper">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="card-title">
                             Please Do Confirm
                            </div>
                        </div>
                        

                        <div class="card-body">
                            <h4 class="card-title text-center">Are You Sure To Delete @Model.RestaurantName ?</h4>
                            
                        </div>
                        <div class="card-footer">
                            <a href="@Url.Action("delete","restaurant")/@Model.RestaurantID" class="btn btn-default" type="button">Yes</a>
                            <a href="@Url.Action("dashboard","home")" class="btn btn-danger pull-lg-right" type="button">No</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@section scripts{
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/vendor.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/elephant.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/application.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/demo.min.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-83990101-1', 'auto');
        ga('send', 'pageview');
    </script>
}

SwiftFoodie/Areas/Admin/Views/Restaurant/Edit.cshtml
@using System.Web.Configuration
@model SwiftFoodie.Models.Restaurants

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,700">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/elephant.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/application.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/demo.min.css">
}

<div class="layout-content-body">
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib">Update @Model.RestaurantName</span>

        </h1>
    </div>
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <form action="@Url.Action("SaveRestaurant","Restaurant")" method="post">
                <div class="demo-md-form-wrapper">
                    <input class="md-form-control" value="@Model.RestaurantID" name="RestaurantID" type="hidden">
                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" value="@Model.RestaurantName" name="RestaurantName" type="text">
                        <label class="md-control-label">Restaurant Name</label>
                    </div>

                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" value="@Model.UserName" name="UserName" type="text">
                        <label class="md-control-label">User Name</label>
                    </div>
                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" value="@Model.Password" name="Password" type="text">
                        <label class="md-control-label">Password</label>
                    </div>

                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" value="@Model.OwnerName" name="OwnerName" type="text">
                        <label class="md-control-label">Owner Name</label>
                    </div>
                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" value="@Model.PhoneNumber" name="PhoneNumber" type="text">
                        <label class="md-control-label">Owner Phone Number</label>
                    </div>

                    <div class="md-form-group md-label-floating">
                        <input class="md-form-control" value="@Model.City" name="City" type="text">
                        <label class="md-control-label">City</label>
                    </div>
                    <div class="md-form-group md-label-floating">
                        <textarea class="md-form-control" rows="4" name="CompleteAddress" maxlength="512"> @Model.CompleteAddress  </textarea>
                        <label class="md-control-label">Complete Address</label>
                    </div>
                    <div class="md-form-group md-label-floating">
                        <button class="btn btn-outline-primary btn-pill" type="submit">Update</button>
                        <a href="@Url.Action("dashboard","home")" class="btn btn-outline-danger btn-pill pull-right" type="reset">Cancel</a>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
@section scripts{
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/vendor.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/elephant.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/application.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/demo.min.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-83990101-1', 'auto');
        ga('send', 'pageview');
    </script>
}

SwiftFoodie/Areas/Admin/Views/Restaurant/alist.cshtml
@using System.Web.Configuration
@model IEnumerable<SwiftFoodie.Models.Restaurants>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,700">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/elephant.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/application.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/demo.min.css">
}

<div class="layout-content-body">
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib text-success">Active Restaurants List</span>

        </h1>
    </div>


    <div class="row gutter-xs">
        @if (Model.Count() > 0)
        {
            foreach (var c in Model) // Print the list
            {
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <div class="media">
                                <div class="media-middle media-body">
                                    <a class="link-muted" href="#">
                                        <strong>@c.OwnerName</strong>
                                    </a>

                                    <a class="link-muted" href="#">
                                        <strong>@c.PhoneNumber</strong>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="card-image">
                            <a class="card-link" href="#">
                                <img class="img-responsive" src="@WebConfigurationManager.AppSettings["Theme"]img/8160313374.jpg" alt="Restaurant Magnifique">
                            </a>
                        </div>

                        <div class="card-body">
                            <h4 class="card-title text-center">@c.RestaurantName</h4>
                            <p class="card-text text-center">
                                <small>@c.CompleteAddress</small>
                            </p>
                        </div>
                        <div class="card-footer">
                            <a href="edit/@c.RestaurantID" class="btn btn-default" type="button">Update</a>
                            <a href="Delete/@c.RestaurantID" class="btn btn-success pull-lg-right" type="button">Do In-Active</a>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <div class="card mt-5">
                <div class="card-body text-center">
                    <div class="alert alert-fill-danger text-danger" role="alert">
                        <i class="icon icon-exclamation-circle"></i>
                        Sorry, Nothing Found
                    </div>
                </div>
            </div>
        }


    </div>
</div>
@section scripts{
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/vendor.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/elephant.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/application.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/demo.min.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-83990101-1', 'auto');
        ga('send', 'pageview');
    </script>
}

SwiftFoodie/Areas/Admin/Views/Restaurant/dlist.cshtml
@using System.Web.Configuration
@model IEnumerable<SwiftFoodie.Models.Restaurants>

@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


@section styles{
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,400italic,500,700">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/vendor.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/elephant.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/application.min.css">
    <link rel="stylesheet" href="@WebConfigurationManager.AppSettings["Theme"]css/demo.min.css">
}

<div class="layout-content-body">
    <div class="title-bar">
        <h1 class="title-bar-title">
            <span class="d-ib text-danger">In-Active Restaurants List</span>

        </h1>
    </div>


    <div class="row gutter-xs">
        @if (Model.Count() > 0)
        {
            foreach (var c in Model) // Print the list
            {
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <div class="media">
                                <div class="media-middle media-body">
                                    <a class="link-muted" href="#">
                                        <strong>@c.OwnerName</strong>
                                    </a>

                                    <a class="link-muted" href="#">
                                        <strong>@c.PhoneNumber</strong>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="card-image">
                            <a class="card-link" href="#">
                                <img class="img-responsive" src="@WebConfigurationManager.AppSettings["Theme"]img/8160313374.jpg" alt="Restaurant Magnifique">
                            </a>
                        </div>

                        <div class="card-body">
                            <h4 class="card-title text-center">@c.RestaurantName</h4>
                            <p class="card-text text-center">
                                <small>@c.CompleteAddress</small>
                            </p>
                        </div>
                        <div class="card-footer">
                            <a href="edit/@c.RestaurantID" class="btn btn-default" type="button">Update</a>
                            <a href="doactive/@c.RestaurantID" class="btn btn-success pull-lg-right" type="button">Do Active</a>
                        </div>
                    </div>
                </div>
            }
        }
            else
            {
                <div class="card mt-5">
                    <div class="card-body text-center">
                        <div class="alert alert-fill-danger text-danger" role="alert">
                            <i class="icon icon-exclamation-circle"></i>
                            Sorry, Nothing Found 
                        </div>
                    </div>
                </div>
            }


    </div>
</div>
@section scripts{
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/vendor.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/elephant.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/application.min.js"></script>
    <script src="@WebConfigurationManager.AppSettings["Theme"]js/demo.min.js"></script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-83990101-1', 'auto');
        ga('send', 'pageview');
    </script>
}